- LICENSE.md
- README.md
- 초기 readme 작성 및 추가
- add MIT license
> :page_facing_up: add readme & license

- src/components/Details/DetailHeader.tsx
- src/components/Details/LeftHeader.tsx
- src/components/Details/RightHeader.tsx
- src/components/Details/SeriesContainer.tsx
- src/components/Details/UDHashContainer.tsx
- src/pages/details/index.tsx
- src/styles/globals.css
(수정 사항에 대한 간략한 한줄 요약/제목)
상세 페이지의 상단 설계 및 스타일
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
* Velog 상세페이지에서 좌측에 좋아요 버튼, 좋아요 카운트, 공유하기 버튼
* 상단 우측에 목차
* 상단 가운데 글 제목 및 해시태그와 시리즈 박스
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)
> 상세 페이지의 상단 설계

- src/components/Home/Card.tsx
(수정 사항에 대한 간략한 한줄 요약/제목)
메인페이지 카드컴포넌트 추가
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 해당 포스트로 이동하는 카드 컴포넌트 제작
- svg 파일 material icon으로 교체완료
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)
> :sparkles: add PostCard component

- src/components/Details/Carousel.tsx
- src/components/Details/DetailHeader.tsx
- src/pages/details/index.tsx
- Carousel 을 설계했습니다. 시리즈에 이전 페이지나 다음 페이지가 없을 경우 버튼을 사라지도록 만들었습니다.
- intro 컴포넌트를 가져와 사용했습니다.
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)
- 최근 커밋을 변경하고 싶은 경우 git commit --amend 를 사용합니다.
> ✨Carousel 설계 (이전, 다음 글)

- src/components/MyPage/MyCard.tsx
- src/components/Search/SearchBar.tsx
- src/pages/search/index.tsx
- yarn.lock
카드 컴포넌트 ui 수정
카드 컴포넌트 패딩 값 변경
mui 적용
-
-
-
-
-
> :lipstick: chage card container padding, add mui

- src/components/MyPage/MyCard.tsx
- src/components/MyPage/Series/DetailCard.tsx
- src/components/MyPage/Series/SeriesCard.tsx
- src/pages/search/index.tsx
시리즈 카드, 시리즈 디테일 카드 ui 추가, constants 수정
- 마이페이지 시리즈 페이지 카드 조건문으로 추가
- 시리즈 페이지 디테일 카드 추가
- constants 불필요 문장 제거
(궁금한 사항들, 하면서 느낀 점 및 공유할 내용)
-
-
> :lipstick: 시리즈, 디테일 카드 ui 추가 및 수정

- src/constants/index.ts
> 💄 update constants

- src/components/Home/Filter.tsx
- src/components/Home/Header.tsx
- src/components/Home/Notice.tsx
- src/components/Home/SelectBox.tsx
- src/pages/index.tsx
- src/pages/list/liked/index.tsx
- src/pages/list/read/index.tsx
- src/pages/recent/index.tsx
- 해시코드 컬러들 PALLETS로 변경
- 읽기목록 UI 구현
> Main page/reading list layout

- src/components/Home/Card.tsx
- 색상 변수 설정
- img태그 Image 태그변경
-
-
-
> :lipstick: mainpage 카드 컴포넌트 변수 설정 및 태그 변경

- src/components/MyPage/Header.tsx
- src/components/MyPage/MyCard.tsx
- src/components/MyPage/Series/DetailCard.tsx
- src/components/MyPage/Series/SeriesCard.tsx
- src/components/Search/SearchBar.tsx
- src/constants/index.ts
- src/pages/search/index.tsx
- styled component 리팩토링
- 컬러를 공통 컬러로 적용
> :lipstick: edit color code, refactor styled-component

- src/components/Editor/BottomMenu.tsx
- src/components/Editor/EditForm.tsx
- src/components/Editor/ToolBar.tsx
- src/components/Editor/WriteForm.tsx
- src/components/Editor/WriteHeader.tsx
- src/components/Home/Card.tsx
- src/constants/index.ts
- src/pages/editor/index.tsx
- src/pages/search/index.tsx
- src/types/Main.ts
- EditForm 컴포넌트 분리
- WirteHeader 컴포넌트 분리
> :recycle: Editor 컴포넌트 구조 변경

- src/components/Search/SearchBar.tsx
- src/pages/search/index.tsx
- search 컴포넌트 value 1초 단위로 query로 전달되게 구현
- search 화면 들어가자마자 포커싱 구현
-
-
> :sparkles: add search query

- package.json
- src/components/MyPage/Series/SeriesEditContainer.tsx
- src/types/Main.ts
- yarn.lock
- series edit container drag and drop 구현
- index 번호는 유지하되 내용은 수정되게 구현
- ui만 조금 수정해주시면 좋을 것 같습니다!
> :sparkles: add draggable list

- src/components/Home/Card.tsx
- src/components/Home/DarkModetoggle.tsx
- src/components/Home/Filter.tsx
- src/components/Home/Header.tsx
- src/components/Home/Notice.tsx
- src/components/Home/SelectBox.tsx
- src/components/MyPage/Header.tsx
- src/constants/index.ts
- src/hooks/useDarkMode.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
- src/pages/list/liked/index.tsx
- src/pages/list/read/index.tsx
- src/pages/recent/index.tsx
- src/styles/global-styles.ts
- src/styles/theme.tsx
✨ 메인페이지 다크모드 기능적용
- 다크모드 기능 구현
- header 컴포넌트에 토글 버튼 삽입
- 메인페이지 다크모드 기능 적용
- 토글 버튼 디자인 변경 예정
- 토글 버튼 위치 어디로 할까요?
- 토글 버튼 디자인  어떻게 바꿀까요?
- 헤더 로고가 현재 캡쳐사진으로 되어있는 데 어떻게할까요?
> ✨  다크모드 기능 구현

- src/components/Common/SkeletonLoading.tsx
- 스켈레톤 로딩 구현
- 아직 컬러가 제대로 안뽑혀서 팔레트에 넣지 않았습니다.
> :sparkles: add skeleton loading

- src/components/Details/DetailCard.tsx
- Home 컴포넌트의 Card를 가져오는 과정에서 Bug가 발생했습니다.
> 🐛 상세 페이지 카드 버그 수정

- src/components/MyPage/MyCard.tsx
- src/components/Search/FindPost.tsx
- src/components/Search/SearchBar.tsx
- src/data/index.ts
- src/pages/search/index.tsx
- src/types/Main.ts
- 서치 기능 구현
- 포스트가 없을 때 검색 결과가 없습니다 뜸
- 제목과 내용에 쿼리문이 포함되는지 여부로 필터
- 필터 된 포스트 개수 연동
- 서치 테스트를 위한 목업 데이터 수정
- 약간의 UI 수정
- 카드 UI를 조금 수정했으니 혹시 이상하면 알려주세요
> :sparkles: add search feature

- src/components/Home/IoTestCardContainer.tsx
- src/data/index.ts
- src/hooks/useIO.tsx
- src/pages/index.tsx
- 카드 컨테이너(무한스크롤 테스트용) 컴포넌트 생성
- 백엔드 연결 시 코드 수정할 예정
- 스켈레톤 로딩 추가 예정
-
> ✨  무한스크롤 테스트용 컨테이너 생성

- src/components/Details/DetailCard.tsx
- src/components/Home/Card.tsx
- src/components/Home/CardContainer.tsx
- src/components/Home/DarkModetoggle.tsx
- src/components/Home/Filter.tsx
- src/components/Home/Header.tsx
- src/components/Home/SelectBox.tsx
- src/data/index.ts
- src/pages/_app.tsx
- src/pages/index.tsx
- src/pages/list/liked/index.tsx
- src/pages/list/read/index.tsx
- src/pages/recent/index.tsx
* 메인페이지 필터링 기능 구현
* 오늘(24시간)/ 이번 주(7일) / 이번 달(1월, 한 달 아님) / 올해(2022년, 1년 아님)
* 다크모드 토클 버튼 위치 및 UI수정
* material 아이콘 사용  
-
> 메인페이지 필터링 기능, 다크 모드 토글버튼 위치 및 UI 수정

- next.config.js
- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/MyCard.tsx
- src/constants/index.ts
- api endpoint 수정
- mypage content api 연동
- mycard 태그 주석처리
- card api 이미지 링크 수정
- mycard 태그로 들어오는 항목이 "['ㄴㄹㅇ', 'ㄴㅇㄹㅇㄴ', 'ㄴㅇㄹㄴㅇ']" 이런 형식이라 일단 주석 처리 했습니다. 이를 해결하기 위한 방법을 구합니다.
- data.data를 해야만 데이터를 받을 수 있는 부분에 대한 토의가 필요합니다.
> :card_file_box: 마이페이지 콘텐츠 데이터 연동, api endpoint 수정

- src/components/Home/IoTestCardContainer.tsx
- src/pages/search/index.tsx
- search 페이지 다이나믹 title 구현
- loTestCardContainer 데이터 수정
> :sparkles: add search dynamic title

- src/components/MyPage/Series/DetailCard.tsx
- src/components/MyPage/Series/SeriesContainer.tsx
- src/components/MyPage/Series/SeriesEditContainer.tsx
- src/constants/index.ts
- src/types/Main.ts
- 💄  update series edit ui style
- ✨  add series sort
- sort 기능 reverse 로 그냥 구현했는데, 리팩토링 할 수 있는 다른 방법이 없을까 생각해보도록 하겠습니다,,
> ✨ upgrade series

- src/components/Common/Header.tsx
- src/components/Common/HeaderMenu.tsx
- src/components/MyPage/MyCard.tsx
- src/components/MyPage/MypageLayout.tsx
- src/components/MyPage/Series/SeriesContainer.tsx
- src/components/MyPage/index.tsx
- src/pages/[id]/series/[title].tsx
- src/pages/details/index.tsx
- 🚚  move header to common folder
- 🐛  fix position error
- 🎨  fix headermenu tags
- 🐛  fix header username error
- ✨  add header animation
- 💚  fix routes error
> 🐛 fix header errors

- src/components/Details/Carousel.tsx
- src/components/Details/Comment.tsx
- src/components/Details/CommentUser.tsx
- src/components/Details/LeftHeader.tsx
- src/components/Details/SeriesContainer.tsx
- src/components/Details/UDHashContainer.tsx
- src/pages/details/index.tsx
- 컴포넌트화 되지 않은 스타일들을 리팩토링 했습니다.
- 상세 페이지에 다크모드를 적용하였습니다.
- SPACE_DEV_CLUB의 대표 COLOR인 보라색의 다크모드 대해 고민중입니다.
> ♻️ Emotion 리팩토링 및 다크모드 적용

- src/components/Common/Header.tsx
- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/MyCard.tsx
- src/components/MyPage/Series/SeriesEditContainer.tsx
- src/hooks/useData.ts
- src/utils/fetcher.ts
- 👽️ update useData
- useData 파일 생성 후 적용
> ⚡️ add useData

- src/components/MyPage/Series/DraggableItem.tsx
- src/components/MyPage/Series/SeriesEditContainer.tsx
> 💄  change series ui

- src/components/Common/HeaderMenu.tsx
- src/components/Common/Tag.tsx
- src/components/MyPage/Menus/SelfIntro.tsx
- src/components/MyPage/Series/SeriesEditContainer.tsx
- src/components/Search/SearchBar.tsx
- src/styles/theme.tsx
- theme 컬러의 색상들을 변경했습니다.
- 페이지들을 모두 체크해보았는데, 혹시라도 빠진 부분이 있을 수 있으니 한 번 더 본인 페이지 컬러확인 부탁드립니다.
> 💄 update theme color

- src/components/Search/SearchBar.tsx
- src/pages/search/index.tsx
- 검색 쿼리가 없다면 아무 카드도 보여지지 않게 수정
- search 페이지 헤더 추가
- search bar 컴포넌트 margin 값 수정
> :sparkles: search 페이지 기능 추가 및 ui 수정

- src/pages/search/index.tsx
> :sparkles: add infinite scroll to search

- src/components/Common/CardLoading.tsx
- src/components/Common/Header.tsx
- src/components/MyPage/Intro.tsx
- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/Menus/SelfIntro.tsx
- src/components/Tags/TagLoading.tsx
- src/components/Tags/TagMainLoading.tsx
- src/pages/tags/[tagname].tsx
- 🚧  fix header link
- 💄  color fix
- 💫  fix header transition
- ♻️  refactor code for skeleton loading
> ♻️ refactor mypages

- src/components/Common/Header.tsx
- src/components/Home/Card.tsx
- src/components/Search/SearchBar.tsx
- src/pages/[id]/index.tsx
- 메인에서 카드를 클릭하면 해당 카드의 아이디를 라우트에 추가
- 라우트에서 아이디를 파싱해서 헤더에 전달
- 선택한 인물의 블로그에서 검색 아이콘을 누르면 ~님이 작성한 포스트 검색 이라고 뜨게함. ~님은 url에서 파싱
- 그냥 메인에서 검색 아이콘을 누르면 뜨지 않음
- 컨플릭트 잘 부탁드리며 질문 언제든 환영합니다.
> :sparkles: 카드를 누르고 아이디를 전달하는 과정 구현

- src/components/Common/CardLoading.tsx
- src/components/Common/Header.tsx
- src/components/Tags/TagLoading.tsx
- src/styles/editor-styles.ts
- src/styles/loading-styled.ts
- 🐛  fix header error
- 💄  add detail tag skeleton loading
- 컨플릭트 체크
> ✨  add CardLoading component

- src/components/MyPage/MyCard.tsx
> :lipstick: add private badge

- src/components/Details/ErrorPage.tsx
- src/pages/[id]/[details]/index.tsx
- 상세 페이지에서 경로가 잘못 될 경우의 404 페이지 생성
- 없음
> ✨상세 페이지의 404 페이지

- src/components/Common/Modal.tsx
- 모달창 UI
- 필요한 함수나 문구를 어떻게 넣을지 고민입니다. 우선 마크업만 진행했는데 필요한 문구가 정해져있다면 배열로 넣을지 그냥 하드코딩으로 해결할지도 모르겠네요.
> :lipstick: add modal component

- src/components/Search/SearchBar.tsx
- search에 url이 검색할 때 마다 쌓여서 뒤로가기가 힘들어지는 현상 해결
> :bug: search에 url 쌓이는 현상 해결

- src/components/Details/DetailCard.tsx
- src/components/Home/Card.tsx
- src/components/Home/CardContainer.tsx
- src/components/Home/DarkModetoggle.tsx
- src/components/Home/Filter.tsx
- src/components/Home/IoTestCardContainer.tsx
✨ 최신순 정렬 구현
- 메인페이지 최신순 정렬
- 7일 이내 작성 글 날짜 형식 변경 (~일 전, 오늘) 
- 다크모드 버튼 반응형
- 오늘 -> 몇 시간 전으로 바꾸는게 좋을까요
> ✨ 최신순 정렬, 7일 이내 작성 글 날짜 형식 변경

- src/components/MyPage/MyCard.tsx
- src/pages/tags/[tagname].tsx
> :beers: api connect

- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/MyCard.tsx
- src/pages/search/index.tsx
- src/pages/tags/[tagname].tsx
- 👽️ change api
- ♻️  refactor code
> ✨  add infinite scroll

- src/components/MyPage/Menus/Content.tsx
> 🐛  fix inifinite loading

- src/components/Common/SkeletonLoading.tsx
- src/components/Search/SearchBar.tsx
- src/pages/search/index.tsx
- 스켈레톤 로딩 ui 수정
- 처음 공백은 검색 안되게 막음
> :lipstick: update skeleton loading, :art: block search empty space

- src/pages/[id]/[details]/index.tsx
- 스키마 구조 변경에 따른 데이터를 다시 연결했습니다.
- map을 각각 두번 돌리던 구조를 한번 돌리는 것으로 코드를 수정했습니다.
- LEEHYUNHO2001 라는 닉네임을 가진 사용자가 Strapi라는 글을 작성했다면
http://localhost:3000/LEEHYUNHO2001/Strapi 에서 상세 페이지를 확인할 수 있습니다.
> ♻️ 변경된 스키마에 따른 데이터 연결

- next.config.js
- src/components/MyPage/MyCard.tsx
- src/components/MyPage/Profile.tsx
- src/components/Search/SearchFilter.tsx
- src/components/Search/SearchHead.tsx
- src/pages/search/index.tsx
- src/types/Main.ts
- 서치 api 연동
- 서치 컴포넌트화, 페이지에는 페이지만
- 타입 열심히 고치겠습니다 살려주세요
> :sparkles: connect search api, :art: split search component

- src/components/Details/Comment.tsx
- src/components/Details/CommentUser.tsx
- src/components/Details/DetailHeader.tsx
- src/components/Details/LeftHeader.tsx
- src/pages/[id]/[details]/index.tsx
- Post의 좋아요 넘버를 Post 데이터의 likepost 길이를 이용하도록 수정했습니다.
- 댓글을 정렬하고 있습니다.
- userinfo에서 유저의 데이터를 가져와 댓글에 정보를 표시하고 있습니다.
- 로그인한 유저의 id와 댓글을 작성한 유저의 id값을 비교하여 자신의 글일 경우 수정 및 삭제 기능이 표시됩니다.
- 대댓글의 경우 들여쓰기와 접기 기능을 구현해야 합니다.
> ✨ 좋아요 기능 수정 및 댓글 구현

- package.json
- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/Menus/ContentData.tsx
- src/hooks/useData.ts
- tsconfig.json
- yarn.lock
- ♻️ separate ContentData component
- ⚡️ change useData
- 🗃️ mypage tag db connect
- ✨ filtering tag by user
- useData 훅을 수정했습니다. 기존 useData를 사용하셨던 분들에게 에러가 나지 않게 만들었으나, 쿼리를 파라미터로 전달 가능하도록 만들었으니 쿼리문을 이용해 request를 보내실 분들은 Content 컴포넌트를 참고해주세요.
> ✨add tags on mypage

- src/pages/_app.tsx
- src/styles/global-styles.ts
- src/styles/theme.tsx
> 🔥  불필요한 코드 삭제

- src/utils/date.ts
- 방금 전, 몇 시간 전 추가
- 지난 달 post의 날짜가 1월 51일 처럼 보이는 버그 수정
> ♻️ 날짜 형식 몇 시간전 추가

- src/components/Details/DetailHeader.tsx
- src/pages/[id]/[details]/index.tsx
- detailpage에서 post 읽었을 때 readingpost db(userid,postid) 전달
- useData 파라미터 변경에 따른 인자 변경
- 리렌더링 문제로 post/put 변경 못함
> detailpage - readingpost 연결

- src/components/Common/Button.tsx
- src/components/Editor/EditorContainer.tsx
- src/components/Editor/EditorInput/BottomMenu.tsx
- src/components/Editor/EditorInput/WriteHeader.tsx
- src/components/Editor/EditorInput/index.tsx
- src/components/Editor/EditorViewer/index.tsx
- src/components/Editor/SubmitModal/SubmitModal.tsx
- src/components/Editor/SubmitModal/index.tsx
- src/components/MyPage/Menus/Content.tsx
- src/styles/theme.tsx
- Button Dark Mode 추가
- Dark Mode Theme에 Button 스타일 추가
- editor 컴포넌트 폴더 경로 수정
> :sparkles: DarkMode toolBar 적용 및 Button Teme 추가

- src/components/MyPage/Menus/BlankPage.tsx
- src/components/MyPage/Menus/ContentData.tsx
- src/components/MyPage/Menus/Series.tsx
- 포스트와 시리즈 데이터가 없는 경우 보여지는 페이지 삽입
> ⚡️ add blank page

- .gitignore
- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/Menus/ContentData.tsx
- src/components/MyPage/MyCard.tsx
- 노트북 사이즈에서 확인할 수 있는 태그 리스트입니다.
> ✨  add large tag filtering

- src/pages/_app.tsx
- src/pages/index.tsx
> :lipstick: remove egg to other pages except main

- src/components/SignUp/SignUp.tsx
- 캐시에서 업데이트 전 데이터를 받아와서 유저 목록 비교를 못하고 있었음
- 회원가입 시 캐시 삭제
-
-
> 🐛  회원가입 후 페이지 전환

- src/components/Details/DetailHeader.tsx
- 테스트ID 변경사항 재적용
- 에러는 해결했지만, 일단 주석처리
-
-
> 🐛  테스트 ID 변경 에러

- src/components/Common/Header.tsx
- src/components/Common/Loading.tsx
- src/components/SignUp/SignUp.tsx
- src/pages/loading.tsx
- 회원가입 시 뒤로가기 버튼이 적용되지 않는 것 해결
- 로그인을 누르고 회원 검증 시간에 로딩창으로 대체
- 컨플릭트 났던것도 있고 해서 가능한 최신화 해 주시고 테스트 해주시면 감사하겠습니다.
> :sparkles: add loading while checking our customer

- .env.production
- src/components/Common/Header.tsx
- src/components/SignUp/SignUp.tsx
- src/constants/index.ts
> :ambulance: 로컬 외에도 로그인 가능하게 수정

- src/components/Details/DetailHeader.tsx
- src/components/Home/IOCardContainer.tsx
- src/pages/[id]/[details]/index.tsx
- 데이터 key값 변경(nickname/profilename)
- Detailpage, mainpage
-
-
-
> 📝 데이터 key값 변경(nickname/profilename)

- src/components/SignUp/SignUp.tsx
- src/pages/loading.tsx
- src/types/Theme.ts
> :sparkles: fix ui

- src/components/Search/SearchFilter.tsx
- src/components/SignUp/SignUp.tsx
- 특정 사람 게시글 서치
- 로그인 로직 컨플릭트 해결
> :sparkles: 특정 사람 게시글 서치 로직 추가

- src/components/Details/Carousel.tsx
- src/components/Details/Comment/Comment.tsx
- src/components/Details/Comment/CommentContainer.tsx
- src/components/Details/Comment/CommentForm.tsx
- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/Comment/ReCommentForm.tsx
- src/components/Details/Comment/index.tsx
- src/components/Details/DetailCard.tsx
- src/components/Details/DetailHeader.tsx
- src/components/Details/LeftHeader.tsx
- src/components/Details/RightHeader.tsx
- src/components/Details/SeriesContainer.tsx
- src/components/Details/UDHashContainer.tsx
- src/components/Details/index.ts
- src/pages/[id]/[details]/index.tsx
- tsconfig.json
- 댓글 생성 기능을 구현했습니다.
- 댓글마다 대댓글 접기 및 숨기기 기능을 구현했습니다.
- 자신의 게시글이거나 댓글이면 수정 및 삭제 버튼이 나타납니다.
-  tsconfig 파일을 수정하고, 절대경로 리팩토링했습니다.
- 댓글을 생성할 때 Strapi DB에 저장되지만 UI에서 실시간 반영이 되지 않고 있습니다.
- 댓글 작성시 textarea 안에 값이 비워지지 않고 있습니다.
> ✨댓글마다 대댓글 접기, 숨기기 기능과 댓글 생성

- src/components/MyPage/Menus/Series.tsx
- src/components/MyPage/Series/DraggableItem.tsx
- src/components/MyPage/Series/SeriesContainer.tsx
- src/components/MyPage/Series/SeriesEditContainer.tsx
- src/components/SignUp/SignUp.tsx
- src/hooks/useData.ts
- src/pages/[id]/series/[title].tsx
- src/types/Main.ts
- ♻️ remove unuseful console.log
- useData 옵션값을 바꿔놓았는데 혹시 에러가 생긴다면 지워도 됩니다.
> ✨ dnd changed index series

- src/components/Details/Comment/CommentForm.tsx
- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/Comment/DeleteModel.tsx
- src/components/Details/Comment/ReCommentForm.tsx
- 댓글과 대댓글 생성 및 삭제 기능을 구현했습니다.
- 대댓글의 group 파악이 불가한 문제점을 해결했습니다.
- 댓글 생성시 group 부여하는 부분을 수정했습니다.
- 댓글 삭제시 대댓글도 삭제하는 기능을 구현했습니다.
- 댓글과 대댓글을 생성하는 Form은 같은 컴포넌트와 같은 로직을 사용합니다.
> 댓글과 대댓글 생성 및 삭제

- src/components/Details/Comment/Comment.tsx
- src/components/Details/Comment/CommentContainer.tsx
- src/components/Details/Comment/CommentForm.tsx
- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/Comment/DeleteModel.tsx
- src/components/Details/Comment/ReCommentForm.tsx
- src/components/Details/Comment/UpdateCommentForm.tsx
- src/components/Details/Comment/index.tsx
- src/components/Details/DetailHeader.tsx
- src/components/Details/UDHashContainer.tsx
- src/utils/date.ts
- 댓글과 대댓글 수정 기능을 추가했습니다.
- CommentForm 컴포넌트에서 props로 넘겨받은 값을 이용하여 
댓글 생성, 대댓글 생성, 댓글 수정, 대댓글 수정을 담당하고 있습니다.
- utils / date에 정상적으로 출력되지 않는 OO일전 문제점을 해결했습니다.
> ✨댓글과 대댓글 수정 기능 추가

- src/utils/date.ts
- 문제점을 해결하는 과정에서 새로운 문제점을 발견하여 수정했습니다.
- x
> 🚑️ 날짜 기능 수정

- src/components/Details/DetailHeader.tsx
- src/components/Home/Card.tsx
- src/components/Home/CardContainer.tsx
- src/components/Home/DarkModetoggle.tsx
- src/components/Home/Filter.tsx
- src/components/Home/ListCard.tsx
- src/components/Home/ListCardContainer.tsx
- src/components/Home/ListCardLoading.tsx
- src/components/Home/Notice.tsx
- src/components/Home/SelectBox.tsx
- src/components/Home/index.tsx
- src/pages/[id]/index.tsx
- src/pages/list/liked/index.tsx
- src/pages/list/read/index.tsx
- src/pages/recent/index.tsx
- Mainpage 및 읽기목록 스켈레톤 로딩
- 절대경로 리팩토링
- 읽기목록 데이터 받아올 때 업데이트 순으로 변경
- desktop 크기일 때, mainpage 카드 컨테이너 width 수정
- postcard -> listcard 변경
- userid, image, thumbnail 연결 안함
> ✨ Mainpage 및 읽기목록 스켈레톤 로딩

- src/components/Details/LeftHeader.tsx
- 포스트 좋아요버튼 빠르게 클릭 시 발생하는 오류를 수정했습니다.
- alert말고 다른 의견 있으시면 알려주시면 감사하겠습니다.
> ♻️ 좋아요 빠르게 클릭 시 발생하는 오류 수정

- src/components/Editor/EditorContainer.tsx
- h1 ~ h4 버튼 클릭시 기능구현
- 클릭된 문자열 위치를 확인해서 (split or match) 몇번째줄인지 확인
- 해당 문자열 앞에 버튼에 맞는 hTag를 추가해준다. "#" + "n번째줄"
- 해당 문자열을 다시 합쳐 (join?) setState에 넣어준다.
- 경우의 수에 따른 오류 발견시 알려주세요.
> :sparkles: h Tag 기능구현

- src/components/Details/Carousel.tsx
- src/components/Details/Comment/Comment.tsx
- src/components/Details/Comment/CommentContainer.tsx
- src/components/Details/Comment/CommentForm.tsx
- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/Comment/DeleteModel.tsx
- src/components/Details/Comment/UpdateCommentForm.tsx
- src/components/Details/DetailCard.tsx
- src/components/Details/DetailHeader.tsx
- src/components/Details/LeftHeader.tsx
- src/components/Details/SeriesContainer.tsx
- src/pages/[id]/[details]/index.tsx
- src/types/Detail.ts
- 상세 페이지 하단에 존재하는 캐러샐에 시리즈 박스에 대한 데이터를 연동했습니다.
- 댓글, 대댓글 생성에 접근제어를 해주고 있습니다.
- 타입을에 대한 것을 types/Detail.ts 에 넣어주었습니다.
- likeposts의 데이터 구조가 변경되면서 LeftHeader에 에러가 발생하고있습니다.
> ✨상세 페이지 하단 시리즈 캐러샐에 데이터 연동

- src/components/Details/LeftHeader.tsx
- src/pages/[id]/[details]/index.tsx
- strapi에서 수정된 post 데이터에 맞춰서 코드 수정하였습니다.
> ♻️ post 데이터 수정에 따른 코드 수정

- src/components/SignUp/SignUp.tsx
- src/pages/api/auth/[...nextauth].ts
- 네트워크 탭에서 모든 회원의 정보를 불러오는 문제 해결
- 로그인 시 엑세스 토큰, 리프레시 토큰 추가
> :lock: 네트워크 탭에서 모든 회원의 정보를 불러오는 문제 해결

- src/components/Details/LeftHeader.tsx
> ♻️ 시리즈 변경 시 좋아요 수 바뀌지 않던 버그 수정

- src/components/Details/Carousel.tsx
- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/DetailCard.tsx
- src/components/Details/DetailHeader.tsx
- src/components/Details/LeftHeader.tsx
- src/components/Details/SeriesContainer.tsx
- src/pages/[id]/[details]/index.tsx
- src/types/Detail.ts
- 페이지 이동시 캐러샐 넘어가지 않는 부분을 해결했습니다.
- 시리즈에 대한 리팩토링을 진행했습니다.
- x
> ♻️ 같은 기능은 부모에서 생성 후 props로 넘겨주기

- src/components/Editor/EditorContainer.tsx
- src/utils/tooBarHTag.ts
:recycle: Head 버튼 utils 분리
- 이중 for문 단축
- 반복되는 함수 utils로 분리
- checkLine 관련 경우의 수가 다양해서 수정을 해야함
> :recycle: H 마크다운 버튼 utils 분리 및 함수 수정

- src/components/Common/ContentData.tsx
- src/components/Common/Header.tsx
- src/components/MyPage/Menus/Content.tsx
-✨  header 로그아웃상태 검색 버튼 링크 추가
-✨  내부 서치 기능 추가
> 서치 관련 기능 추가

- src/components/Editor/EditorContainer.tsx
- src/components/Editor/EditorInput/ToolBar.tsx
- src/components/Editor/EditorInput/WriteForm.tsx
- src/utils/toolBarCheckLine.ts
- src/utils/toolBarChkBtn.ts
- :sparkles: quote 기능 구현
- :recycle: head와 quote 중복되는 코드 utils로 리팩토링
- :recycle: 사용하지 않는 utils 제거
- 줄을 구분하는 조건문의 경우의 수에 따른 오류 해결 필요
> :sparkles: quote 기능 구현

- src/utils/date.ts
> ♻️ date.ts 로직 수정

- README.md
> 📝update readme

- src/components/Home/ListCardContainer.tsx
- posts 데이터에 likeposts 필드 추가해서 좋아요 수 count 하게 수정했습니다.
> ♻️ ListCard 좋아요 수 count 수정

- src/components/Common/LoginErrorPage.tsx
- src/components/Home/CardContainer.tsx
- src/components/Home/Filter.tsx
- src/components/Home/ListCardContainer.tsx
- src/utils/date.ts
- 최신, 트렌딩 카드에 좋아요 수 추가
- card container 반응형 max-width 수정
- 1시간 이내 작성된 게시글 시간 오류 수정
- 비로그인으로 읽기목록 페이지 접속 시 로그인이 필요합니다 이미지 출력
> ♻️ 최신, 트렌딩 카드에 좋아요 수 추가

- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/DetailHeader.tsx
- src/components/Details/LeftHeader.tsx
- src/components/Details/RightHeader.tsx
- src/components/Details/UDHashContainer.tsx
- src/pages/[id]/[details]/index.tsx
- RightHeader와 Series 에 대한 에러 처리
- LikePost, ReadingPost 에러 처리
- 관심있는 포스트 -> 없는 경우 고려
- 댓글 생성시 group 설정 수정
- 유저의 글 목록으로 리다이렉트
- 댓글 생성시 대댓글을 달 수 있는 UI가 새로고침해야 보이는 현상이 있습니다.
> 자잘한 에러처리 및 버그 수정

- src/pages/_document.tsx
- src/pages/index.tsx
> :chart_with_upwards_trend: add google analytics

- src/components/MyPage/MyCard.tsx
> :bug: search 뒤로가기 오류

- src/components/Search/SearchBar.tsx
> :bug: block enter key

- src/components/Home/CardContainer.tsx
- src/components/Home/Filter.tsx
- src/components/Home/ListCardContainer.tsx
- Mainpage의 CardContainer, Filter와 Common의 Header 간의 반응형 조건이 일치하지 않아 기준점에서 스타일이 달라지는 현상 발생. 
- Mainpage의 CardContainer, Filter 반응형 조건을 max-width로 변경하여 통일시킴.
> 💄  CardContainer, Filter, Header 반응형 조건 max-width로 통일

- src/components/Home/CardContainer.tsx
- src/components/Home/ListCardContainer.tsx
- src/types/Main.ts
- mainpage에서 post api 연동 시 데이터 값 구조분해할당 하였습니다.
- post 타입에서 user, likeposts, comment 업데이트 했습니다.
- listpost 타입 추가했습니다.
> mainpage 리팩토링 및 post type 업데이트

- src/components/Editor/EditorContainer.tsx
- src/components/Editor/EditorInput/LinkInputModal.tsx
- src/components/Editor/EditorInput/ToolBar.tsx
- src/components/Editor/EditorInput/WriteForm.tsx
- toolBar 클릭시 링크 모달이 나타남
- 스트럭쳐 구현
- textarea 안으로 모달을 커서 위치에 맞춰 움직이게 하는 방법을 고민중
- codeMirror
> :sparkles: 링크 모달 세팅

- src/components/Common/Header.tsx
- src/components/Common/HeaderMenu.tsx
- src/components/Common/Loading.tsx
- src/components/Editor/EditorContainer.tsx
- src/components/MyPage/Intro.tsx
- src/components/MyPage/Menus/Series.tsx
- src/pages/[id]/[details]/index.tsx
- header 프롭스로 받은 이름을 블로그 이름으로, 메뉴는 로그인한 유저로 설정
- intro에 유저 이미지가 없는 경우 기본 이미지로 저장되도록 저장
- 콘솔 삭제
> 🐛  header와 intro 에러 수정 및 프롭스 변경

- src/components/Details/LeftHeader/LeftHeader.tsx
- src/pages/[id]/[details]/index.tsx
- src/types/Detail.ts
- 공유하기 미리보기를 위한 메타태그 수정
- 비로그인 시 게시글 좋아요 수 0으로 나오던 버그 수정
- Kakao.init 중복 실행되어서 게시글 진입할 수 없던 버그 수정
> ✨ 포스트 상세페이지 meta tag 추가, 각종 버그 수정

- src/components/Details/LeftHeader/Share.tsx
- src/pages/[id]/[details]/index.tsx
- 상세 페이지가 공유되지 않고 홈 부분만 공유되는 버그 해결
- 공유하기 부분을 커스텀 하여 이미지와 버튼을 넣어주었습니다.
> 상세 페이지 공유 안되는것 해결 및 커스텀

- next.config.js
- package.json
- src/components/MyPage/Menus/SelfIntro.tsx
- src/components/MyPage/Menus/Series.tsx
- src/components/MyPage/Menus/WrappedEditor.tsx
- src/pages/[id]/[details]/index.tsx
- src/pages/_app.tsx
- src/styles/theme.tsx
- yarn.lock
- 📦  toastUI 설치
- 💬  theme에 현재 모드를 나타내는 TYPE 추가
- ✨  자기 소개 에디터 기능 추가
- 🐛  에디터 self 에러 수정
- 🚚 자기소개 해당 블로그 주인의 데이터로 연결 및 체크 후 버튼 수정 권한 설정
- toast editor ui 사용했습니다. yarn 으로 설치 후 실행해주시길 바랍니다.
> 마이페이지 자기 소개 UI 및 기능 구현

- src/components/Common/Tag.tsx
- src/components/MyPage/MyCard.tsx
- src/components/Search/SearchFilter.tsx
> :bug: fix search link

- src/components/Details/Comment/CommentContainer.tsx
- src/components/Details/DetailHeader/UDHashContainer.tsx
- 게시글 삭제 기능을 구현
- 게시글 삭제시 해당 게시글의  댓글과 대댓글을 찾아 모두 삭제
> ✨게시글 삭제 및 게시글에 달린 댓글과 대댓글 삭제

- src/components/Search/SearchFilter.tsx
> :bug: add private filtering

- src/components/Home/CardContainer.tsx
- src/components/Home/ListCard.tsx
- src/components/Home/ListCardContainer.tsx
- 비공개 게시물 필터링 (private false게시물만 나오며, true나 null인 게시물은 나오지 않습니다)
- 유저 기본 이미지소스 오타 수정
> ✨  비공개 게시물 필터링

- src/components/Details/DetailCard.tsx
- src/components/Home/CardContainer.tsx
- src/components/Home/ListCard.tsx
- src/components/Home/ListCardContainer.tsx
- src/types/Detail.ts
- 메인페이지 desc(소개글) 없는 포스트 content(본문) 대체
- 관심있을만한 포스트 desc(소개글) 없는 포스트 content(본문) 대체
- desc(소개글) 마지막 줄 말줄임 스타일 추가
-
-
> ♻️ 메인페이지 desc 없는 포스트 content 대체

- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/DetailHeader/SeriesContainer.tsx
- src/components/Details/DetailHeader/UDHashContainer.tsx
- src/components/Details/RightHeader.tsx
- src/pages/[id]/[details]/index.tsx
- src/styles/global-styles.ts
- 목차 클릭 시 해당 위치로 스크롤 이동
- 부드러운 스크롤 이동
- 위치에 따른 목차 스타일
- 각종 UI 수정
> 목차 클릭 시 해당 위치로 스크롤 이동 및 스타일 적용

- package.json
- src/components/Details/LeftHeader/Share.tsx
- src/pages/[id]/[details]/index.tsx
- src/pages/_document.tsx
- yarn.lock
- 디테일 메타태그 url 수정
- meta tag 동적 세팅을 위해서 SSR을 구현했습니다.
- next-seo를 추가해서, 풀받으시면 yarn 하셔야합니다.
> 🐛 디테일 메타태그 url 수정

- src/components/Home/Filter.tsx
- src/components/Home/Notice.tsx
- src/components/Home/SelectBox.tsx
- Mainpage style props 구조분해할당
- Filter, Notice, SelectBox
> ♻️  mainpage style props 구조분해할당

- src/pages/[id]/[details]/index.tsx
- SSR 부분에 한글 URL일 경우 인코딩된 정보와 비교하여
데이터를 불러오도록 오류를 해결했습니다.
> 🐛 한글 URL 인코딩 되어 게시글을 찾지 못하는 오류 해결

- src/components/Common/Header.tsx
- src/components/Editor/EditorContainer.tsx
-  :sparkles: submit 전송 완료시 메인페이지로 이동
- :sparkles:  Header 새글작성 버튼 링크 추가
> :sparkles: submit 전송 완료시 메인페이지로 이동 및 Header 새글작성 버튼 링크 추가

- src/components/Common/ContentData.tsx
- src/components/Home/ListCardContainer.tsx
- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/MyCard.tsx
- src/components/Search/SearchFilter.tsx
- src/components/SignUp/SignUp.tsx
- src/pages/search/index.tsx
- ✨ 비공개 게시글 마이페이지에서 본인만 보이도록 설정
- ✨ 서치 쿼리 수정
> 비공개 게시글 사용자 권한에 따른 조건 수정

- src/components/Details/LeftHeader/LeftHeader.tsx
- src/components/Home/CardContainer.tsx
- src/components/Home/ListCard.tsx
- 게시글 좋아요 시 post의 likes +1
- 트렌딩 좋아요 순 정렬 
- post의 likes 필드가 추가되었고, 글 생성하면 자동 0으로 설정됩니다.
- 예전에 작성된 post들은 likes가 null이라, 메인에서 볼수가 없습니다.
> ♻️  좋아요 기능 수정, 트렌딩 좋아요 순 정렬

- src/components/Details/DetailHeader/DetailHeader.tsx
- src/components/Home/ListCard.tsx
- src/hooks/useReadingData.ts
- src/types/Main.ts
🏷️  ListPost 타입 업데이트
- useReadingData 최근 읽은 포스트 hook 생성
- ListPost 타입 업데이트
> ✨ useReadingData 최근 읽은 포스트 hook 생성

- src/components/Editor/EditorContainer.tsx
- src/components/Editor/SubmitModal/SubmitModal.tsx
- url 기본값 title에서 추출 연동
- 띄어쓰기 있을시 여백 "-"로 대체 정규표현식 적용
- infoPost 기본값 contents에서 추출 연동
- value Chk 추가
> :sparkles: infoPost 및 url 작성된 글에 맞게 기본 값 추가 및 value chk 추가현

- src/components/Common/Loading.tsx
- src/components/Home/CardContainer.tsx
- CardContainer.tsx , Loading.tsx 테스트 콘솔 삭제
> 🔥  테스트 콘솔 코드 삭제

- README.md
> :bento: 리드미 데이터 구조 사진 업데이트

- src/components/Editor/EditorContainer.tsx
- src/components/Editor/EditorInput/BottomMenu.tsx
- src/hooks/useData.ts
:sparkles: 나가기 버튼 구현
:sparkles: 임시저장 구현
- 나가기 버튼 구현
- 임시저장시 title로 url 구성
- 임시저장시 private default로 post
- 임시저장 후 로직 고민해볼 필요가 있습니다.
> :sparkles: editor 하단 메뉴 버튼 기능 구현

- src/components/Common/ContentData.tsx
- src/components/MyPage/Menus/Content.tsx
- src/components/MyPage/Menus/SelfIntro.tsx
- 🐛  비회원이 마이페이지 접근 불가능한 에러 해결
- 🐛 해쉬태그 데이터 에러 수정
- ✨ 해쉬태그 private 체크
> 마이페이지 에러 수정

- src/components/MyPage/Menus/Content.tsx
- src/types/Detail.ts
> 🐛 fix mypage error

- src/components/Details/Comment/Comment.tsx
- src/components/Details/Comment/CommentForm.tsx
- src/components/Details/Comment/CommentFormContainer.tsx
- src/components/Details/Context/ContextStore.ts
- src/components/Details/Context/PostProvider.tsx
- src/components/Details/Context/index.ts
- src/components/Details/DetailCard.tsx
- src/components/Details/DetailContainer.tsx
- src/components/Details/DetailHeader/DetailHeader.tsx
- src/components/Details/DetailHeader/UDHashContainer.tsx
- src/components/Details/LeftHeader/LeftHeader.tsx
- src/components/Details/LeftHeader/Share.tsx
- src/components/Details/RightHeader.tsx
- src/components/Details/index.ts
- src/pages/[id]/[detail]/index.tsx
- src/types/detail/DetailContext.ts
- src/utils/shuffle.ts
- post user 정보를 가져오는 부분을 수정하여 상세 페이지 하단에서 게시글 작성자의 정보를 확인할 수 있습니다.
- Context API 관심사의 분리를 수행했습니다. (postStore 선언)
- import 선언 순서를 리팩토링하고 있습니다.
> Detail 페이지 게시글 작성자 표시 및 ContextAPI 리팩토링

- src/components/Details/DetailContainer.tsx
- src/components/Details/DetialNavigation.tsx
- src/components/Details/index.ts
- src/hooks/index.ts
- 목차의 모든 요소에 대해 클릭 이벤트가 동작합니다.
- 목차 아이템 클릭시 Viewer에서 해당 위치로 스크롤이 이동합니다.
- 게시글을 읽은 진행도를 출력하고 있습니다.
> Detail Navigation 기능 수정

- package.json
- src/components/Details/LeftHeader/LeftHeader.tsx
- src/components/Details/LeftHeader/helper/deleteLike.ts
- src/components/Details/LeftHeader/helper/getLikeData.ts
- src/components/Details/LeftHeader/helper/getLoggedUserIsLike.ts
- src/components/Details/LeftHeader/helper/index.ts
- src/components/Details/LeftHeader/helper/postLike.ts
- src/components/Details/LeftHeader/helper/putPostLike.ts
- yarn.lock
- 첫 렌더링시 로그인한 유저가 현재 게시글에 좋아요를 눌렀는지 체크하는 로직에 버그가 있어 해결했습니다.
- 좋아요 취소시 해당 유저의 likepost가 제거되도록 구현했습니다.
- 좋아요를 여러번 클릭할 경우 delete가 2번째에서 block되는 문제점을 해결했습니다.
- Post의 Like Number은 사용하지 않아도 무방하여 해당 비지니스 로직을 분리해놓았습니다.
- likepost length값을 이용하고 있습니다.
- 아직 리팩토링 중입니다.
> 좋아요 기능 버그 수정 및 리팩토링

- src/components/Common/Modal.tsx
- src/components/Details/Comment/Comment.tsx
- src/components/Details/Comment/CommentForm.tsx
- src/components/Details/Comment/DetailComments.tsx
- src/components/Details/Comment/helper/CommentForm/createFetcher.ts
- src/components/Details/Comment/helper/CommentForm/index.ts
- src/components/Details/Comment/helper/CommentForm/updateFetcher.ts
- src/components/Details/Comment/helper/CommentForm/useGetCommentData.ts
- src/components/Details/Comment/helper/DetailComments/currentCommentGroup.ts
- src/components/Details/Comment/helper/DetailComments/groupByComments.ts
- src/components/Details/Comment/helper/DetailComments/index.ts
- src/components/Details/Comment/helper/DetailComments/sortCommets.ts
- src/components/Details/Comment/index.tsx
- src/components/Details/DetailCard.tsx
- src/components/Details/DetailContainer.tsx
- src/components/Details/DetailInterested.tsx
- src/components/Details/DetailMain/DetailMain.tsx
- src/components/Details/LeftHeader/LeftHeader.tsx
- src/components/Details/index.ts
- 댓글 데이터를 받는 부분을 관심사의 분리 했습니다.
- 댓글 CRUD시 실시간 적용 안돼는 부분을 mutation이 될 수 있도록 리팩토링 했습니다.
- 댓글 Delete시 화면이 고정되는 버그를 해결했습니다.
> 댓글 mutation 적용 및 delete 시 모달 버그 해결
